[package]
name = "truncatable"
version = "0.1.0"
authors = ["Nickolai <nickolaivassiliev@gmail.com>"]
edition = "2018"
license = "GPL-3.0-only"
description = "Small crate for truncatable strings"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
